added usage:

diff --git a/decryptdir b/decryptdir
--- a/decryptdir
+++ b/decryptdir
@@ -1,15 +1,22 @@
 #!/bin/bash
+
+if [ -z $1 ] || [ -n $2 ] ;
+  then
+    echo "Usage: decryptdir <dir-name(without .ssl_enc)>"
+    exit 1;
+fi
+
 clear
 if [ ! -f $1.ssl_enc ] || [ -z $1 ]
-    then
-	echo ""
-	echo "------------------------------------------------------------------------"
-	echo ""
-	echo $"	     Error: file \"$1\" does not exist or is wrong file type"
-	echo ""
-	echo "------------------------------------------------------------------------"
-	echo ""
-	exit 1 
+  then
+    echo ""
+    echo "------------------------------------------------------------------------"
+    echo ""
+    echo $"	     Error: file \"$1\" does not exist or is wrong file type"
+    echo ""
+    echo "------------------------------------------------------------------------"
+    echo ""
+    exit 1; 
 fi
 echo ""
 echo "------------------------------------------------------------------------"
diff --git a/encryptdir b/encryptdir
--- a/encryptdir
+++ b/encryptdir
@@ -1,15 +1,22 @@
 #!/bin/bash
+
+if [ -z $1 ] || [ -n $2 ] ;
+  then
+    echo "Usage: encryptdir <dir-name>"
+    exit 1;
+fi
+
 clear
 if [ ! -d $1 ] || [ -z $1 ] ;
-    then
-	echo ""
-	echo "------------------------------------------------------------------------"
-	echo ""
-	echo $"		    Error: Directory \"$1\" does not exist"
-	echo ""
-	echo "------------------------------------------------------------------------"
-	echo ""
-	exit 1 
+  then
+    echo ""
+    echo "------------------------------------------------------------------------"
+    echo ""
+    echo $"	hellow   Error: Directory \"$1\" does not exist"
+    echo ""
+    echo "------------------------------------------------------------------------"
+    echo ""
+    exit 1; 
 fi
 echo ""
 echo "------------------------------------------------------------------------"
