improved exception handling.

diff --git a/decryptdir b/decryptdir
--- a/decryptdir
+++ b/decryptdir
@@ -1,11 +1,15 @@
 #!/bin/bash
 
+usage(){
+    echo "Usage: encryptdir [dir-name to encrypt]"
+    exit 1;
+}
+
 filename=$1
 
 if [ ! $filename ] || [ $2 ] ;
   then
-    echo "Usage: decryptdir <encrypted filename>"
-    exit 1;
+	usage
 fi
 
 if [ $? -eq 0 ] ;
@@ -13,43 +17,33 @@ if [ $? -eq 0 ] ;
     filename=(${1//./ });
 fi
 
+set +e
 sslname="$filename.ssl_enc"
 tarname="$filename.tar.gz"
-clear
 if [ ! -e $sslname ] ;
   then
-    echo ""
-    echo "------------------------------------------------------------------------"
-    echo ""
-    echo " Error: file \"$sslname\" does not exist or is wrong file type"
-    echo ""
-    echo "------------------------------------------------------------------------"
-    echo ""
+    echo "Error: file \"$sslname\" does not exist or is wrong file type"
     exit 1; 
 fi
 
-echo ""
-echo "------------------------------------------------------------------------"
-echo ""
-echo "               Decrypting $sslname into $tarname"
-echo "     [using openssl aes-256-cbc -d -a -in $sslname -out $tarname]"
-echo ""
-echo "------------------------------------------------------------------------"
-echo ""
-
 openssl aes-256-cbc -d -a -in $sslname -out $tarname
+if [ $? -ne 0 ]; 
+  then
+    echo "ERROR: could not decrypt \"$sslname\""
+    exit 1;
+fi
 
-echo ""
-echo "------------------------------------------------------------------------"
-echo ""
-echo "                  Successfully decrypted $sslname"
-echo "              decompressing [using tar -xvzf $tarname $filename]" 
-echo ""
-echo "------------------------------------------------------------------------"
-echo ""
+tar -xzf $tarname $filename 
+if [ $? -ne 0 ]; 
+  then
+    echo "ERROR: could not decompress \"$tarname\""
+    exit 1;
+fi
+set -e
 
-tar -xvzf $tarname $filename 
+if [ -d $filename ] ;
+  then
+    rm $sslname
+fi
 
-echo ""
-echo "cleaning ..."
 rm $tarname 
diff --git a/encryptdir b/encryptdir
--- a/encryptdir
+++ b/encryptdir
@@ -1,20 +1,19 @@
 #!/bin/bash
 
-if [ $# -ne 1 ];
-  then
-    echo "Usage: encryptdir <dir-name to encrypt>"
+usage(){
+    echo "Usage: encryptdir [dir-name to encrypt]"
     exit 1;
+}
+
+if [ $# -gt 2 ] || [ $# -eq 0 ];
+  then
+    usage
 fi
 
 if [ ! -d $1 ] ;
   then
-    echo ""
-    echo "------------------------------------------------------------------------"
-    echo ""
-    echo "	        Error: Directory \"$1\" does not exist"
-    echo ""
-    echo "------------------------------------------------------------------------"
-    echo ""
+    echo "Error: Directory \"$1\" does not exist"
+    usage
     exit 1; 
 fi
 
@@ -25,38 +24,29 @@ if [ "$lastChar" = "/" ] ;
     exit 1;
 fi
 
-echo ""
-echo "------------------------------------------------------------------------"
-echo ""
-echo "    Compressing $1 to $1.tar.gz [using: tar -cvzf $1.tar.gz $1]"
-echo ""
-echo "------------------------------------------------------------------------"
-echo ""
-echo "Compressing..."
-echo ""
-
+foldername=$1
 set +e
 tarname="$1.tar.gz"
-tar -cvzf $tarname $1
-
-if [ $? -eq 2 ]; 
+tar -czf $tarname $1
+if [ $? -ne 0 ] ; 
   then
-    echo "tar has encountered an error"
+     echo "ERROR: could not compress \"$tarname\""
+    exit 1;
+fi
+
+sslname="$1.ssl_enc"
+openssl aes-256-cbc -a -salt -in $tarname -out $sslname
+if [ $? -ne 0 ] ; 
+  then
+    echo "ERROR: could not encrypt \"$sslname\""
+    rm $tarname
     exit 1;
 fi
 set -e
 
-sslname="$1.ssl_enc"
-echo ""
-echo "------------------------------------------------------------------------"
-echo ""
-echo "                  Encrypting $tarname to $sslname"
-echo "   [using: openssl aes-256-cbc -a -salt -in $tarname -out $sslname"
-echo ""
-echo "------------------------------------------------------------------------"
-echo ""
+if [ -a $sslname ] ;
+  then
+    rm -rf $foldername
+fi
 
-openssl aes-256-cbc -a -salt -in $tarname -out $sslname
-echo ""
-echo "Cleaning..."
 rm $tarname 
